syntax = "proto3";

package openswarm.api;

option go_package = "openswarm/api/gen";

import "api/proto/types.proto";

service CoordinatorService {
    rpc InitializeTask(InitTaskRequest) returns (InitTaskResponse);
    rpc RelayForward(RelayRequest) returns (RelayResponse);
    rpc GetCoordinatorHealth(GetCoordinatorHealthRequest) returns (CoordinatorHealthResponse);
}

message Pipeline {
    repeated string worker_ids = 1;
}

message InitTaskRequest {
    string session_id = 1;
    string prompt = 2;
    string model_id = 3;
}

message InitTaskResponse{

}

message RelayRequest {
    Vector vector = 1;
    string worker_id = 2;

}

message RelayResponse {}

message GetCoordinatorHealthRequest {}

message CoordinatorHealthResponse {
    bool status = 1;
    string latency = 2;
}
