syntax = "proto3";

package openswarm.api;

option go_package = "openswarm/api/gen";


// WorkerService handles worker-related operations. A worker is a decentralized
// node in the network that holds sharded layers of an LLM and some experts.
service WorkerService {
  rpc Heartbeat(HeartbeatRequest) returns (HeartbeatResponse);
  rpc ConnectToCoordinator(ConnectToCoordinatorRequest) returns (ConnectToCoordinatorResponse);
}

message HeartbeatRequest {
  string worker_id = 1;
}

message HeartbeatResponse {
  bool accepted = 1;
}

message ConnectToCoordinatorRequest {
  string addr = 1;
}

message ConnectToCoordinatorResponse {
  bool accepted = 1;
}
